name: Autograding Tests

on:
  - push
  - workflow_dispatch
  - repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check if home_directory.txt exists anywhere in the repository
      run: |
        if find . -name "home_directory.txt" | grep -q "home_directory.txt"; then
          echo "home_directory.txt exists."
        else
          echo "home_directory.txt does not exist."
          exit 1
        fi

    # Example of additional autograding tests
    # - name: Run tests
    #   uses: classroom-resources/autograding-io-grader@v1
    #   with:
    #     test-name: Addition Test
    #     id: addition-test
    #     command: "./bin/add.sh"
    #     input: 1 2
    #     expected-output: 3
    #     comparison-method: exact
    #     timeout: 10

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      with:
        runners: check-file
